---
title: "Seminar 2b"
author: "Louis-Alexandre Fournier"
date: "January 8, 2018"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#STAT 540 Seminar 2B

#Part 1 - First time ggplot-ing

```{r tidyverse}
library(tidyverse)
```

###Do cars with big engines use more fuel than cars with small engines? 
####mpg dataset
```{r mpg dataframe}
mpg
```
####Highway miles per gallon in function of engine displacement (L)
```{r ggplot of mpg}
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy))
```

```{r barebones graphing template}
ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy))
ggplot(data = mpg) + geom_density_2d(mapping = aes(x = displ, y = hwy))
```

####City miles per gallon in function of engine displacement (L)
```{r ggplot of mpg for cty}
ggplot(data = mpg) + geom_point(mapping = aes(x= displ, y = cty))
```

####Aestethic mappings
#####color
```{r aesthetic color}
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = class))
```
#####size
```{r aesthetic size}
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, size = class))
```

